modLoader="kotlinforforge" #mandatory
loaderVersion="[5.1,)" #mandatory
license="MPL-2.0"
issueTrackerURL="https://github.com/JustPyrrha/PyTek/issues" #optional

[[mods]] #mandatory
modId="pytek" #mandatory
version="0.1.0-alpha.0" #mandatory
displayName="PyTek" #mandatory
updateJSONURL="https://api.modrinth.com/updates/pytek/forge_updates.json" #optional
displayURL="https://github.com/JustPyrrha/PyTek/" #optional
logoFile="pytek.png" #optional
#credits="" #optional
authors="JustPyrrha" #optional
description='''beep boop''' #mandatory
#displayTest="MATCH_VERSION" #optional

#[[mixins]]
#config="pytek.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.pytek]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[20.6,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.pytek]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"

#[features.pytek]
#openGLVersion="[3.2,)"
